"""
Django settings for bluebird project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
from pymongo import MongoClient

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4e=yzl^9*yvnsu9_s0zi@&d+!_*5pww%y=wqlr+p9-!5zcv(gk'

# CLOUDINARY_NAME = 'dctpwwktp'
# CLOUDINARY_API_KEY= '187221122313249'
# CLOUDINARY_API_SECRET = 'nT19TbT1fZDoS0s-vb2sDjQLYkg'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
PAYTM_MID = "BuleBi25513150470208"
PAYTM_MKEY = "qcq@AkIqQi7fJgtk"

# PAYTM_MID="zsrTOT97098816716861"
# PAYTM_MKEY="UI5sQlaKPwjzlFb1"

ALLOWED_HOSTS = ['*']

CORS_ORIGIN_ALLOW_ALL = True
# CORS_ORIGIN_WHITELIST = (
#    'http://localhost:4200',
#     'http://localhost:8500',
#     'http://127.0.0.1:8686',
#     'http://admin.mahalaxmikirana.com',
#     'https://admin.mahalaxmikirana.com',
#     'http://testingservers.ddns.net:4000',
#     'http://mahalaxmikirana.com',
#     'https://mahalaxmikirana.com',
#     'http://3.109.1.110:8500',
# )

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)


CORS_ALLOW_HEADERS = (
    'pageType',
    'userType',
    'textCode',
    'token',
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'feesapp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bluebird.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bluebird.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'CLIENT': {
            # 'host': 'mongodb+srv://DJTech:admin123@cluster0.vzcsg.mongodb.net/?retryWrites=true&w=majority',
            'host': 'mongodb+srv://Admin:Admin123@cluster0.zqmgx.mongodb.net/?retryWrites=true&w=majority',
            'name': 'bluebirduserDB',
            'username': 'Admin',
            'password': 'Admin123',
            # 'authMechanism': 'SCRAM'
        }
    }
}



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mydatabase',
        'USER': 'root',
        'PASSWORD': 'Arjun@123',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# DATABASES = {
#    'default': {
#       'ENGINE': 'djongo',
#      'CLIENT': {
#         'host': 'localhost',
#        'name':'testdb1',
#       'username': '',
#      'password': '',
#     'port': 27017
# 'authMechanism': 'SCRAM'
#  }
#  }
# }
# localdb =  MongoClient("mongodb://localhost:27017/testdb")
client = MongoClient(
    "mongodb+srv://Admin:Admin123@cluster0.zqmgx.mongodb.net/?retryWrites=true&w=majority")

admindb = client.AdminDB

client1 = MongoClient(
    "mongodb+srv://Admin:Admin123@cluster0.zqmgx.mongodb.net/?retryWrites=true&w=majority")
userdb = client1.bluebirduserDB

# client2 = MongoClient("mongodb://localhost:27017/")
# localdb = client2.testdb1
# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / 'media'
