# Generated by Django 3.2.13 on 2022-06-26 11:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'AdminUser',
            },
        ),
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('class_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ClassModel',
            },
        ),
        migrations.CreateModel(
            name='LateFees',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('perday', 'perday'), ('percentage', 'percentage'), ('fixamount', 'fixamount')], max_length=100, null=True)),
                ('fees', models.FloatField(blank=True, max_length=15, null=True)),
                ('lastdate', models.DateField()),
                ('installment', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'LateFees',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('school_name', models.CharField(blank=True, max_length=500, null=True)),
                ('school_discription', models.CharField(blank=True, max_length=500, null=True)),
                ('school_logo', models.ImageField(upload_to='school')),
            ],
            options={
                'db_table': 'School',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('scolar_no', models.CharField(editable=False, max_length=500, primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=500, null=True)),
                ('father_name', models.CharField(blank=True, max_length=500, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=500, null=True)),
                ('RTE', models.BooleanField(default=False)),
                ('Full_paid', models.BooleanField(default=False)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classId', to='feesapp.classmodel')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='StudentFees',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('installment1', models.FloatField(blank=True, null=True)),
                ('installment2', models.FloatField(blank=True, null=True)),
                ('installment3', models.FloatField(blank=True, null=True)),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to='feesapp.student')),
            ],
            options={
                'db_table': 'StudentFees',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('amount', models.FloatField(blank=True, default=False, null=True)),
                ('type', models.CharField(blank=True, choices=[('cheque', 'cheque'), ('DD', 'DD'), ('cash', 'cash')], max_length=100, null=True)),
                ('discription', models.CharField(blank=True, max_length=255, null=True)),
                ('createdOn', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('scolarno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scolarno', to='feesapp.student')),
            ],
            options={
                'db_table': 'PaymentMethod',
            },
        ),
        migrations.CreateModel(
            name='FeesStructure',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('installment1', models.FloatField(blank=True, null=True)),
                ('installment2', models.FloatField(blank=True, null=True)),
                ('installment3', models.FloatField(blank=True, null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feestr_class_id', to='feesapp.classmodel')),
            ],
            options={
                'db_table': 'FeesStructure',
            },
        ),
        migrations.AddField(
            model_name='classmodel',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_id', to='feesapp.school'),
        ),
    ]
